# Generated by Django 5.0.2 on 2026-03-23 19:25

import careers.models
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentOpenning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('job_title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(default='INDORE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobOpeningDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.currentopenning')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppliedCandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('candidate_resume', models.FileField(upload_to='candidate_resume/', validators=[careers.models.validate_file_size])),
                ('candidate_portfolio', models.FileField(blank=True, null=True, upload_to='candidate_portfolio/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('current_location', models.CharField(max_length=50)),
                ('notice_period', models.CharField(max_length=50)),
                ('current_ctc', models.CharField(max_length=20)),
                ('expected_ctc', models.CharField(max_length=20)),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.jobopeningdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
