# Generated by Django 5.0.2 on 2024-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcandidateprofile',
            name='candidate_portfolio',
            field=models.FileField(blank=True, null=True, upload_to='candidate_portfolio/'),
        ),
    ]
