# Generated by Django 5.0.2 on 2024-02-17 15:58

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
