# Generated by Django 5.0.2 on 2024-02-17 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_jobdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('candidate_resume', models.FileField(upload_to='candidate_resume/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('current_location', models.CharField(max_length=50)),
                ('notice_period', models.CharField(max_length=50)),
                ('current_ctc', models.IntegerField()),
                ('expected_ctc', models.IntegerField()),
                ('job_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='careers.jobdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
