# Generated by Django 5.0.2 on 2024-05-13 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_appliedcandidateprofile_candidate_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcandidateprofile',
            name='job_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.jobopeningdetail'),
        ),
    ]
