# Generated by Django 5.0.2 on 2024-02-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_candidateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_ctc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='expected_ctc',
            field=models.CharField(max_length=20),
        ),
    ]
