# Generated by Django 5.0.2 on 2024-02-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
