# Generated by Django 5.0.2 on 2024-02-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_slider_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_images',
            new_name='project_banner_image',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=544),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(default=54),
            preserve_default=False,
        ),
    ]
