# Generated by Django 5.0.2 on 2024-02-13 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project_image',
            field=models.ImageField(upload_to='project_images/'),
        ),
    ]
