# Generated by Django 5.0.2 on 2024-02-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projectimage_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='client_img',
        ),
    ]
