# Generated by Django 5.0.2 on 2024-02-13 16:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
