# Generated by Django 5.0.2 on 2024-02-13 16:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aboutus_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
