# Generated by Django 5.0.2 on 2024-02-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_aboutus_content_aboutus_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='team_members/')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
