# Generated by Django 5.0.2 on 2024-02-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_project_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='ClientReview',
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
