# Generated by Django 5.0.2 on 2024-02-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_footercontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_img',
        ),
    ]
