# Generated by Django 5.0.2 on 2024-02-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_service_service_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactform',
            name='mobile_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
