# Generated by Django 5.0.2 on 2024-02-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
