# Generated by Django 5.0.2 on 2024-02-15 18:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_contactform_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('price', models.IntegerField()),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projectcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
