# Generated by Django 5.0.2 on 2024-02-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('client_logo', models.ImageField(upload_to='clients_images/')),
                ('client_name', models.CharField(max_length=50)),
                ('client_site', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
