# Generated by Django 5.0.2 on 2024-02-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='social_profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
