# Generated by Django 5.0.2 on 2024-02-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_teammember_social_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='is_project_last_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project_short_des',
            field=models.TextField(blank=True, help_text='Fill this field if is project last image is checked!', null=True),
        ),
    ]
