# Generated by Django 5.0.2 on 2024-05-13 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_project_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cat', to='core.projectcategory'),
        ),
    ]
