# Generated by Django 5.0.2 on 2024-05-28 10:17

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_project_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpage',
            name='client_logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='clients_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_banner_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='slider_images/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='team_members/'),
        ),
    ]
