# Generated by Django 5.0.2 on 2025-08-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_projectimage_is_project_last_image_and_more'),
        ('core', '0028_alter_clientpage_client_logo_and_more'),
    ]

    operations = [
    ]
